# Generated by Django 4.2.7 on 2023-11-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_questionariorespondido_data_realizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_submetida',
        ),
    ]
