# Generated by Django 4.2.7 on 2023-11-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_questionariorespondido_respostas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alternativa_submetida',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
